FROM maven:3.9.9-eclipse-temurin-21

WORKDIR /workspace

COPY pom.xml .
COPY mvnw mvnw.cmd ./
COPY .mvn ./.mvn

RUN chmod +x mvnw && ./mvnw -B dependency:go-offline || mvn -B dependency:go-offline

ENV SPRING_PROFILES_ACTIVE=dev
ENV MAVEN_OPTS="-Dmaven.repo.local=/root/.m2/repository"

EXPOSE 8080

CMD ["sh", "-c", "chmod +x mvnw && ./mvnw spring-boot:run"]
